version: '3.8'

services:
  pylint:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: ["pylint", "*.py"]

  terraform:
    image: hashicorp/terraform:latest
    working_dir: /terraform
    volumes:
      - ./terraform:/terraform
