version: '3.8'

services:
  pylint:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: ["pylint", "*.py"]

  terraform:
    image: hashicorp/terraform:latest
    working_dir: /terraform
    volumes:
      - ./terraform:/terraform

  toybox:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - SECRETS_ENVIRONMENT=${SECRETS_ENVIRONMENT}
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: [ "python", "./sample.py" ]
