name: Main CI
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  execute-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Docker Compose
        run: |
          docker-compose run pylint
