name: Main CI/CD

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  execute-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Docker Compose
        run: |
          docker-compose run pylint

  execute-cd:
    needs: execute-ci
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "ap-northeast-1"
          role-to-assume: ${{ vars.AWS_DEPLOY_ROLE }}

      - name: Login To ECR
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Checkout
        uses: actions/checkout@v4

      - name: build and push docker image to ecr
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: "discord_toybox"
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build . --tag gh_build 
          docker tag gh_build ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
          docker tag gh_build ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest
